### PR TITLE
Dynamic SubLayer Reorder Sample

### PR DESCRIPTION
**Pull request by salihyalcin**
I've added dynamic sublayer reorder sample. It helps user to use drag drop functionality on their map applications.

### CODE REVIEW

**Comment by doneill** [comment]
@salihyalcin Thanks for providing this sample, on first take it seems like a very useful sample.  I will give this a full review after you address the couple of minor updates I will respond back to you to better integrate your sample with the repo.

**Comment by salihyalcin** [comment]
Due to ramadan feast, my commits delayed. Now you can check changes.

**Comment by salihyalcin** [comment]
What about this sample's last status? Will this sample be added to current samples ?

**Comment by doneill** [comment]
@salihyalcin We will review for including. Thanks for updating based on my first limited review, more to come.

**Comment by doneill** [comment]
@salihyalcin Can you take another look at your PR, I am not able to get it to run.  First issue had to do with ```java.lang.illegalStateException: You need to use a Theme.AppCompat``` I fixed that by updated your styles.xml file:  

```xml
<style name="AppTheme" parent="@style/Theme.AppCompat">
```

But now I am getting issues with a ```ClassCastException``` on line 31.  

Please take another look and provide fixes so the app runs.  I think this is a very nice sample and will try to include if you can get it running again and after a code review.

**Comment by salihyalcin** [comment]
@doneill I've made some fixes. Now app will run.

**Comment by doneill** [comment]
@salihyalcin I have reviewed your updates and tested your sample.  I am keen to merge, but am missing a README.md file.  Can you provide one that details how to use the app and any programmatic features you would like to share?  Please look at other samples to get an idea of the type of content we require.

**Comment by salihyalcin** [comment]
I've provided README.md file :+1: If you want, you can merge ^^

**Comment by doneill** [comment]
Thanks @salihyalcin I will review, thanks for your effort and updates.

**Comment by doneill** [comment]
Thanks @salihyalcin There are some minor things I may address but overall this is a very good sample.  Thanks for you efforts to contribute to our samples and your patience in going through the review process. Welcome as an official contributor!

**Comment by salihyalcin** [comment]
Thanks for this opportunity. I'm so proud of to be as an official contributor :)

**Pull request merged**
