### PR TITLE
Refactored to apply server edits and show updated callout

### PR DESCRIPTION
**Pull request by manishk3189**
Hi @doneill Can you please review the PR which addresses [#1151](https://devtopia.esri.com/runtime/java-android-sdk/issues/1151) and displays callout with updated feature type after edits.

### CODE REVIEW

**Comment by doneill** [comment]
@mani8177 Fix looks good, but the feature service has reduced features such that they are only showing up over North America.  Can you change the view point such that it centers on North America and we see the features when the app opens?

**Comment by manishk3189** [comment]
@doneill, the layer was full of features earlier I guess they cleaned it up recently. I will update all such samples to center on North America

**Comment by manishk3189** [comment]
@doneill The view point is adjusted to North America now

**Comment by doneill** [comment]
@manishk3189 Updates look good, will merge.

**Pull request merged**
