### PR TITLE
Fix for issue #915

### PR DESCRIPTION
**Pull request by mani8177**
@doneill 
1. Updated Readme file with reference to Google docs on how to use the geo command
2. GPS on/off check and prompt to turn on gps

### CODE REVIEW

**Comment by mani8177** [comment]
Updated the readme files

**Comment by doneill** [comment]
@mani8177 Please create a local branch off of your master in future PR's.  I will review this one as is.

**Comment by mani8177** [comment]
Yes, I will create a local branch going forward. Thanks

**Comment by doneill** [comment]
Closing this PR as updates are provided in #53

**Pull request closed without merging**
