### PR TITLE
addressed read/write permission to the apps 

### PR DESCRIPTION
**Pull request by XuemingRocks**
to allow downloading and editing of attachments.

### CODE REVIEW

**Comment by XuemingRocks** [comment]
@rchintapalli @doneill could you review this change?

**Comment by rchintapalli** [comment]
@XuemingRocks It works fine now. As expected.

**Comment by XuemingRocks** [comment]
thanks @rchintapalli. @doneill good to merge??

**Comment by doneill** [comment]
@XuemingRocks Yep, merging now.

**Pull request merged**
