### PR TITLE
Updated sample with search widget and LocatorSuggestion API

### PR DESCRIPTION
**Pull request by XuemingRocks**
...olkit to show search result.

### CODE REVIEW

**Comment by XuemingRocks** [comment]
changes for #28

**Comment by XuemingRocks** [comment]
@doneill could you review? thanks.

**Comment by doneill** [comment]
@XuemingRocks UI looks great!  

One UX design suggestion: Can you have the keyboard drop out and return to full map after a successful search?  Currently the keyboard remains and if you hit the back button to remove it your search goes away.  

I updated the README screenshot to reflect the new UI. 

Otherwise everything looks good and a great improvement to the sample.

**Comment by XuemingRocks** [comment]
@doneill change made. review? thanks.

**Comment by doneill** [comment]
@XuemingRocks looks good, will merge

**Pull request merged**
