### PR TITLE
Trev8939/basemap styles all

### PR DESCRIPTION
**Pull request by TADraeseke**
PR to update the last of our old basemaps to the new basemapstyles

### CODE REVIEW

**Comment by shubham7109** [comment]
I'll assign myself to this PR.

**Review by shubham7109 — APPROVED** [review]
Everything looks good while running it on the sample viewer.

**Review by saratchandrakarumuri — APPROVED** [review]

**Comment by shubham7109** [comment]
Moved the branch merge to `v.next` instead.

**Comment by shubham7109** [comment]
Moved the merge branch to `v.next` from `main`

**Pull request merged**
