### PR TITLE
Trev8939/show labels on layers

### PR DESCRIPTION
**Pull request by TADraeseke**
Adds sample according to issue: https://devtopia.esri.com/runtime/common-samples/issues/309

@john0005 - Can you review the Android java version please?
@tschie - Can you review the Android kotlin version please?

Thanks!

### CODE REVIEW

**Comment by john0005** [comment]
@TADraeseke My first android review how cool!

**Comment by TADraeseke** [comment]
PR fixes in. Can you have a second look @john0005 ? Thanks!

**Comment by TADraeseke** [comment]
@tschie - Our other samples all use a folder called 'java' to hold kotlin files. Its auto-generated by Android Studio and is a pain to get around. Will look into doing this as a total effort across the whole kotlin samples project at a later date.

**Comment by tschie** [comment]
@TADraeseke That's fine.

**Pull request merged**
