### PR TITLE
Rename generate geodatabase

### PR DESCRIPTION
**Pull request by shubham7109**
## Description
With the addition the of `Create mobile geodatabase` sample, renamed the sample from 
- `Generate Geodatabase` -> `Generate geodatabase replica from feature service`

- Update the README.md title, screenshot title, relevant metadata (`"redirect_from"`, etc.), folder name
- Update file path & sample file names 
- Add `replica` to the tags (within README.md & README.metadata.json)

## Links and Data
Sample Epic: `runtime/common-samples/issues/3712 `

## What To Review
- See the sample runs as expected with the new name

### CODE REVIEW

**Comment by shubham7109** [comment]
The metadata check is failing, worth checking out the cause here

**Review by TADraeseke — APPROVED** [review]
Sorry for the delay with metadata checker. All tests passing now (I did have to make some changes to both README and metadata to be compliant:

- Offline Data -> Offline data
- Append relavant API to end of keywords list in metadata

**Review by saratchandrakarumuri — COMMENTED** [review]
Looks like only the kotlin sample is modified and java sample is left untouched... Due to this when whole viewer is built we are seeing both old `Generate geodatabase` sample and this new one. If the reason for this change is to avoid confusion with `Create mobile geodatabase` I feel Java sample also needs to be renamed.

**Comment by shubham7109** [comment]
@saratchandrakarumuri  Good catch, thanks! Renamed both the Java and the Kotlin version of the `Generate Geodatabase` sample.

**Comment by shubham7109** [comment]
@TADraeseke Requesting a re-review to review the changes for the Java sample rename.

**Review by TADraeseke — APPROVED** [review]
LGTM! Nice catch @saratchandrakarumuri -- I'd forgotten we had a java version!

**Comment by shubham7109** [comment]
Thanks Trevor! Ready for verification @saratchandrakarumuri

**Review by saratchandrakarumuri — APPROVED** [review]

**Comment by XuFei1021** [comment]
你好，来信已收到，请放心。

**Pull request merged**
